Repository CMU-313/fall-2021-hw4-crabs-adjust-humidity, pull requests merged in 2021-11, with the labels that each got.

#11 Basic testing skeleton for the microservice
  dockerfile/apps/tests/test_predict_model.py
Labels: testing

#15 Updated API call
  dockerfile/apps/app.py
Labels: enhancement

#17 Validate query params in API call
  dockerfile/apps/app.py
Labels: enhancement

#18 Add the required documentation
  README.md
Labels: documentation

#20 update test_predict_model.py
  dockerfile/apps/tests/test_predict_model.py
Labels: testing
